javascripts:
  app:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery_ujs.js    
    - public/javascripts/application.js        
stylesheets:
  app:
    - public/stylesheets/*.css
